name: java CI with maven

on:
  push:
    branches: ["main", "dev", "prod-support","mystery"]
  pull_request:
    branches: ["main", "dev", "prod-support", "mystery"]



jobs:


    build:
      name: Application Build
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/Setup-java@v4
          with:
            distribution: temurin
            java-version: 21
        - name: Maven Package
          run: mvn -B clean package




